### ISSUE TITLE
Examples using selmer?

### ISSUE THREAD

**Issue by andyparsons** [magnars/optimus#32]
Wondering if there are any examples using optimus asset loaders in a luminus/selmer project? We are keen to try optimus but struggling to wire everything up!

**Comment by magnars** [comment]
I don't have any experience with luminus or selmer, but I would be happy to answer any questions you have. What have you tried? Do these frameworks expose the Ring middleware stack somewhere?

**Comment by andyparsons** [comment]
Luminus makes us of ring and compojure, so yes. Selmer is a Django-like templating library into which I'd like to inject Optimus asset URLs. Let me poke around further and come back with a very specific issue. Thanks!

**Comment by andyparsons** [comment]
For example, this view function should render the bundle output into the Selmer template (the bracketed content is simply passed into the template). But, this actually outputs the string "clojure.lang.LazySeq@1" so we must be missing a step somewhere.

```clojure
(defn style-guide [request]
  (layout/render
    "admin/styleguide.html" 
    {:page-style (optimus.hiccup/link-to-css-bundles request ["app.css"])}))
```

**Comment by magnars** [comment]
Ah yes, that is a bit convoluted if you're not using hiccup. In fact, I've been meaning to change it to be less hiccup-specific. I'll fix that on the train home, and push a new version.

If you want to have it working straight away, include hiccup in your project `[hiccup "1.0.4"]` then require `[hiccup.core :refer [html]]` and do:

```clj
(defn style-guide [request]
  (layout/render
    "admin/styleguide.html" 
    {:page-style (html (optimus.hiccup/link-to-css-bundles request ["app.css"]))}))
```

**Comment by andyparsons** [comment]
Ah, of course Dumb mistake not to get the HTML out of hiccup. Thanks. FWIW, more friendliness to Selmer, which is the default templating engine in Luminus would be great for adoption. I think Optimus' approach and flexibility is superior by far to the other options out there.

**Comment by magnars** [comment]
Glad to hear that. :) I wouldn't call it a dumb mistake as much as a dumb API. I'll get a new version out soon.

**Comment by magnars** [comment]
I've released `[optimus "0.17.0"]`, which removes the `optimus.hiccup` namespace in favor of `optimus.html`.

The old `optimus.hiccup/link-to-css-bundles` created hiccup data structures, which is a mistake. It's specific to one rendering method, and Hiccup works just as well (or better) with strings.

You can replace `optimus.hiccup` with `optimus.html`, remove hiccup, and all should be well. :)

**Comment by andyparsons** [comment]
@magnars thanks for the super-fast update! Trying it now and will report back if any questions pop up.

**Comment by magnars** [comment]
This one had been brewing for a while, so thanks for giving me the proper incentive to do something about it. :)

**Comment by andyparsons** [comment]
Great. Still having an issue in a new context, would be grateful if you could point out anything that's incorrect.

I have defined a simple asset bundle:
```closure
(defn get-assets [] 
  (concat 
   (assets/load-bundle "public" 
                       "app.css" 
                       ["/css/screen.css"
                        "/css/test.scss"]))
```
and inserted the middleware:
```clojure
(def development-middleware
  [wrap-error-page
   wrap-exceptions
   #(optimus/wrap % get-assets optimizations/all strategies/serve-frozen-assets)])
```
then attempt to render the assets link in the view (:page-style rendered into the Selmer template):
```clojure
(defn style-guide [request]
  (layout/render
    "admin/styleguide.html" 
    {:page-style (optimus.html/link-to-css-bundles request ["app.css"])}))
```
This results in no assets link in my page, unfortunately.

**Comment by andyparsons** [comment]
Great. Note I removed my last note here, the issue was unrelated to your recent change.
